### ISSUE TITLE
Idle Manager not compatible with Firefox

### ISSUE THREAD

**Issue by salldredge-r7** [planttheidea/react-idle-manager#8]
`isIdle` and `isTimedOut` forever stay false in Firefox
![image](https://user-images.githubusercontent.com/29072528/46632687-7c031d80-cb19-11e8-968b-dbd4a9337c4a.png)

hahaha you know how much we miss you

**Comment by planttheidea** [comment]
Is this not an issue anymore? Haha I'm confused.

**Comment by salldredge-r7** [comment]
No, it's working fine locally by itself in Firefox 😬... but IDR is not timing out in Firefox 😬  which is a different issue.... 😬

**Comment by planttheidea** [comment]
Ah ... Good luck. 😁

**Comment by salldredge-r7** [comment]
😬
